#!/usr/bin/expect -f
set timeout 600

spawn scp -o StrictHostKeyChecking=no -r /home/anuhas/programming/Capsulehouse-Customization/supabase/functions/. root@178.104.127.220:/root/supabase/supabase/docker/volumes/functions/
expect "password:"
send "voibVmIdk9DqPMmZ\r"
expect eof

spawn scp -o StrictHostKeyChecking=no -r /home/anuhas/programming/happypetal-customization/supabase/functions/. root@178.104.127.220:/root/supabase/supabase/docker/volumes/functions/
expect "password:"
send "voibVmIdk9DqPMmZ\r"
expect eof
