#!/usr/bin/expect -f
set timeout 60

spawn scp -o StrictHostKeyChecking=no /home/anuhas/programming/Capsulehouse-Customization/supabase/functions/wsender-sessions-capsulehouse/index.ts root@178.104.127.220:/root/supabase/supabase/docker/volumes/functions/wsender-sessions-capsulehouse/index.ts
expect "password:"
send "voibVmIdk9DqPMmZ\r"
expect eof

spawn scp -o StrictHostKeyChecking=no /home/anuhas/programming/happypetal-customization/supabase/functions/wsender-sessions-happypetal/index.ts root@178.104.127.220:/root/supabase/supabase/docker/volumes/functions/wsender-sessions-happypetal/index.ts
expect "password:"
send "voibVmIdk9DqPMmZ\r"
expect eof
