#!/usr/bin/expect -f
set timeout 60
spawn scp -o StrictHostKeyChecking=no create_triggers_flexlearn.sh root@178.104.127.220:/root/supabase/supabase/docker/
expect "password:"
send "voibVmIdk9DqPMmZ\r"
expect eof

spawn ssh -o StrictHostKeyChecking=no root@178.104.127.220 "cd /root/supabase/supabase/docker && chmod +x create_triggers_flexlearn.sh && ./create_triggers_flexlearn.sh"
expect "password:"
send "voibVmIdk9DqPMmZ\r"
expect eof
